# -*- coding: utf-8 -*-
"""my_week_appv2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ITaDHKMNB3g9tU_Y-K7_U_Z1LFhEJDSY
"""

import streamlit as st
import matplotlib.pyplot as plt
import pandas as pd
from io import BytesIO
import base64
import datetime

st.set_page_config(layout="centered")

# Load Google Font
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Pacifico&display=swap');
    html, body, [class*="css"] {
        font-family: 'Pacifico', cursive;
        background-color: #FFF8F0;
        color: #3E3E3E;
    }
    h1 {
        color: #FF69B4;
        text-align: center;
    }
    .stButton>button {
        background-color: #FFB6C1;
        color: black;
        border-radius: 12px;
        padding: 10px;
    }
    </style>
""", unsafe_allow_html=True)

st.title("📊 My Week in Numbers")

# Name Input
name = st.text_input("Your Name", "Madhu")

# Date Range Input
col1, col2 = st.columns(2)
with col1:
    start_date = st.date_input("From", datetime.date.today() - datetime.timedelta(days=7))
with col2:
    end_date = st.date_input("To", datetime.date.today())

st.markdown("---")

# Weekly Metrics
sleep = st.slider("Sleep (hrs)", 0, 70, 49)
steps = st.slider("Steps (in 1000s)", 0, 100, 32)
tea = st.slider("Tea (cups)", 0, 20, 10)
books = st.slider("Books Read", 0, 10, 1)
screen = st.slider("Screen Time (hrs)", 0, 50, 18)

labels = ['Sleep', 'Steps', 'Tea', 'Books', 'Screen Time']
values = [sleep, steps, tea, books, screen]
colors = ['#6A5ACD', '#20B2AA', '#FF8C00', '#FF69B4', '#2E8B57']

# Weekly Bar Chart
fig, ax = plt.subplots(figsize=(6, 3))
bars = ax.barh(labels, values, color=colors)
for bar in bars:
    ax.text(bar.get_width() + 0.5, bar.get_y() + 0.1, f'{bar.get_width()}', fontsize=9)
ax.set_title(f"{name}'s Weekly Stats", fontsize=12)
ax.set_xticks([])
ax.set_facecolor('#FFF8F0')
fig.patch.set_facecolor('#FFF8F0')
st.pyplot(fig)

# Download Snapshot Button
buffer = BytesIO()
fig.savefig(buffer, format="png")
buffer.seek(0)
b64 = base64.b64encode(buffer.read()).decode()
href = f'<a href="data:file/png;base64,{b64}" download="{name}_week_snapshot.png">📥 Save This Snapshot</a>'
st.markdown(href, unsafe_allow_html=True)

# Sidebar – Monthly Pie Chart for Smart Spending
st.sidebar.title("🧾 This Month's Summary")
categories = ['Food', 'Transport', 'Shopping', 'Entertainment', 'Other']
spending = [3000, 1500, 4000, 1000, 800]
colors_side = ['#FFD700', '#FF7F50', '#ADFF2F', '#40E0D0', '#FF69B4']

fig2, ax2 = plt.subplots()
ax2.pie(spending, labels=categories, autopct='%1.1f%%', startangle=90, colors=colors_side)
ax2.axis('equal')
st.sidebar.pyplot(fig2)

# Footer
st.markdown("---")
st.markdown("<p style='text-align: center;'>Developed with 💖 by AmsuMadhuDeepikaOruganti</p>", unsafe_allow_html=True)