# -*- coding: utf-8 -*-
"""my_week_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YEDt5DfhT9gfIOpfnfGaoWJZFqa8EA-e
"""

# my_week_app.py
import streamlit as st
import matplotlib.pyplot as plt

# Custom page config
st.set_page_config(page_title="My Week in Numbers", page_icon="📊", layout="centered")

# Background & font style
st.markdown("""
    <style>
    body {
        background-color: #FFF0F5;
        font-family: 'Comic Sans MS', cursive;
    }
    .stApp {
        background-color: #FFF0F5;
    }
    h1 {
        color: #8A2BE2;
        font-family: 'Trebuchet MS';
    }
    .footer {
        font-size: 14px;
        color: gray;
        text-align: center;
        margin-top: 50px;
    }
    </style>
""", unsafe_allow_html=True)

# Title
st.title("📊 My Week in Numbers")

# Inputs
sleep = st.slider("Sleep (hrs)", 0, 70, 49)
steps = st.slider("Steps (in 1000s)", 0, 100, 32)
tea = st.slider("Tea (cups)", 0, 20, 10)
books = st.slider("Books Read", 0, 10, 1)
screen = st.slider("Screen Time (hrs)", 0, 50, 18)

# Chart
labels = ['Sleep', 'Steps', 'Tea', 'Books', 'Screen Time']
values = [sleep, steps, tea, books, screen]
colors = ['#6A5ACD', '#20B2AA', '#FF8C00', '#FF69B4', '#2E8B57']

fig, ax = plt.subplots()
bars = ax.barh(labels, values, color=colors)
for bar in bars:
    ax.text(bar.get_width() + 0.5, bar.get_y() + 0.2, f'{bar.get_width()}', fontsize=10)
ax.set_title("Your Weekly Stats")
ax.set_xticks([])
st.pyplot(fig)

# Footer
st.markdown("<div class='footer'>✨ Developed by AmsuMadhuDeepikaOruganti ✨</div>", unsafe_allow_html=True)